version: '3.1'

services:
  php:
    build: ./.docker/php
    container_name: ${COMPOSE_PROJECT_NAME}-php
    working_dir: /application
    volumes:
      - ./:/application
      - ./.docker/log:/var/log


